### ISSUE TITLE
Update to work with algoliasearch v5

### ISSUE THREAD

**Issue by indie-ridge-dev** [sanity-io/sanity-algolia#29]
Hi, I'm using this plugin and it's great, I upgraded to algoliasearch v5@alpha and the indexing seems to have stopped working. Does this mean a new version of the plugin will be developed?

Thanks!

**Comment by runeb** [comment]
Hello @indie-ridge-dev. We may update to newer API in the future, but we will not support alpha versions

**Comment by james2doyle** [comment]
@runeb Looks like v5 is out now: https://github.com/algolia/algoliasearch-client-javascript/releases/tag/5.0.0

Is there a timeline for the tweaks to make this work? Or would a PR be necessary?
