### ISSUE TITLE
Update to work with Sanity Studio v3

### ISSUE THREAD

**Issue by Slgoetz** [sanity-io/sanity-algolia#34]
Currently this is is not listed to work with the new Studio v3. It would be great if we could get a timeline for that update.

**Comment by multiplehats** [comment]
Would be great to have a least the deps updated. The Client types are outdated

**Comment by runeb** [comment]
This module does not depend on Studio V3, so we have updated the documentation on exchange and will be releasing a new version of this module which does not depend on `@sanity/client`

@multiplehats Please file a different bug report if you are having unrelated issues. Thanks!
