### ISSUE TITLE
How do I transform your code for require- rather than import-based functions?

### ISSUE THREAD

**Issue by kkgthb** [sanity-io/sanity-algolia#9]
I'm trying to use Netlify with your example function instead of Vercel.  I'm getting errors about `@import` and saw a tip to switch to `require` imports instead.

However, I keep getting failures like `TypeError: sanityAlgolia.webhookSync is not a function` or `TypeError: indexer is not a function`.

Any tips?

**Comment by runeb** [comment]
Hello @kkgthb . If you are using `require` you might need to get the default export. A better way is to use `babel` or some other bundler/transpiler when you deploy javascript code.

Try

```javascript
const sanityAlgolia = require("sanity-algolia").default';
```
